
async function init () {
  console.log(234)
}

init().catch((err) => {
  console.log(err)
})
